FROM continuumio/miniconda3

COPY ./ /chinese_words

WORKDIR /chinese_words

RUN conda env create --name chinese_words --file /chinese_words/environments/environment.yml
RUN echo "conda activate chinese_words" >> ~/.bashrc

EXPOSE 5000

ENV PATH /opt/conda/envs/chinese_words/bin:$PATH

ENV FLASK_APP=flask_app

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
