FROM continuumio/miniconda3

COPY ./ /<app_name>

WORKDIR /<app_name>

RUN conda env create --name <app_name> --file /<app_name>/environments/environment.yml
RUN echo "conda activate <app_name>" >> ~/.bashrc

EXPOSE 5000

ENV PATH /opt/conda/envs/<app_name>/bin:$PATH

ENV FLASK_APP=flask_app

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
